### ISSUE TITLE
Website link is not working. 

### ISSUE THREAD

**Issue by neillp** [sahilkalkal9/resume-hub#1]
Hi, I'm looking for someone to develop a simple resume (CV) tool for our website. Unfortunately your contact link is not working.

**Comment by sahilkalkal9** [comment]
Hii, sorry for the inconvenience
Our website Resume Hub is under development but it's sure that after
sometime you will be able to build your resume for 100% free.
Many templates will be there.

Thanks & Regards

**Comment by sahilkalkal9** [comment]
Website is working now properly.

**Comment by neillp** [comment]
Thank you. I'll have a look. Sent from my phone-------- Original message --------From: Sahil Kalkal ***@***.***>Date: Fri, 10 Feb 2023, 17:16To: sahilkalkal/resume-hub ***@***.***>Cc: Neill ***@***.***>, Author ***@***.***>Subject: Re: [sahilkalkal/resume-hub] Website link is not working.  (Issue #1)
Website is working now properly.
